"""empty message

Revision ID: 24a13df6abaf
Revises: 487fc80c3576
Create Date: 2022-11-08 19:57:47.408324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24a13df6abaf'
down_revision = '487fc80c3576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Benchmark_id', sa.String(), nullable=False),
    sa.Column('Benchmark_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'Benchmark_id')
    )
    # ### end Alembic commands ###
