"""empty message

Revision ID: 2dbbd44cbacf
Revises: c353ce5a2338
Create Date: 2022-11-08 20:13:42.754809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbbd44cbacf'
down_revision = 'c353ce5a2338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.String(), nullable=False),
    sa.Column('benchmark_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark')
    # ### end Alembic commands ###
