"""empty message

Revision ID: c353ce5a2338
Revises: 24a13df6abaf
Create Date: 2022-11-08 20:08:59.410072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c353ce5a2338'
down_revision = '24a13df6abaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('benchmark_id', sa.String(), nullable=False),
    sa.Column('benchmark_description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'benchmark_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benchmark')
    # ### end Alembic commands ###
